{{- if eq .Values.deploymentType "frontend" -}}
apiVersion: v1
data:
  cluster-local: "false"
  console: "true"
  console-authentication: internal
  console-password: "rubble"
  console-user: "barney"
  edge: "false"
  name: west-site
  router-console: "true"
  service-controller: "true"
  service-sync: "true"
kind: ConfigMap
metadata:
  name: skupper-site
  labels:
    {{- include "skuppersample.labels" . | nindent 4 }}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   labels:
#     {{- include "skuppersample.labels" . | nindent 4 }}
#     skupper.io/type: connection-token-request
#   name: west-secret
{{- end }}
