---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tests.example.example.com
spec:
  # When set to true, CRs with unknown fields are rejected
  preserveUnknownFields: false
  group: example.example.com
  names:
    kind: Test
    listKind: TestList
    plural: tests
    singular: test
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
  version: v1alpha1
  validation:
    openAPIV3Schema:
      description: Test is the Schema for the tests API
      properties:
        apiVersion:
          description: ''
          type: string
        kind:
          description: ''
          type: string
        metadata:
          type: object
        spec:
          description: Spec defines the desired state of Test
          type: object
          properties:
            myString:
              pattern: ^[a-zA-Z]+$
              type: string
            myBool:
              type: boolean
            myObject:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            myInt:
              type: integer
              minimum: 1
              maximum: 10
        status:
          description: Status defines the observed state of Test
          type: object
      type: object
  subresources:
    status: {}
