# permissions for end users to view skuppersamples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skuppersample-viewer-role
rules:
- apiGroups:
  - skuppersample.example.com
  resources:
  - skuppersamples
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - skuppersample.example.com
  resources:
  - skuppersamples/status
  verbs:
  - get
